diemMonNMKT = input("Moi ban nhap diem mon Nhap Mon Ky Thuat: ")
print("Diem Nhap Mon Ky Thuat: ",diemMonNMKT)
print("Kieu du lieu: ",type(diemMonNMKT))
print()
diemMonDSTT= int(input("Moi ban nhap diem mon Dai So Tuyen Tinh: "))
print("Diem Dai So Tuyen Tinh: ",diemMonDSTT)
print("Kieu du lieu: ",type(diemMonDSTT))
